### ISSUE TITLE
max_depth leads to high CPU usage

### ISSUE THREAD

**Issue by joelrich** [bmoscon/cryptofeed#210]
With the following configuration, the CPU usage is around 30%:
```
  BITMEX:
    l2_book:
      symbols: [XBTUSD]
      book_delta: true
```
With the following configuration, it is around 95%:
```
  BITMEX:
    l2_book:
      symbols: [XBTUSD]
      book_delta: true
      max_depth: 10000
```
