### ISSUE TITLE
Bybit - error in BTC-USDT pair

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#343]
**Describe the bug**
With following config file.
```yaml
    BYBIT:
        channel_timeouts:
            trades: 90
            l2_book: 90
        retries: -1
        trades: [BTC-USDT,BTC-USD]
        l2_book:
            symbols: [BTC-USDT,BTC-USD]
            book_delta: true
            book_interval: 100000
```

I got following error (running from Cryptostore).
```yaml
2020-12-03 08:48:27,257 : ERROR : BYBIT: Error from exchange {'success': False, 'ret_msg': 'error:invalid filter:BTCUSDT', 'conn_id': '7c94d1fe-ff93-4ba6-b8f3-7c800620e31a', 'request': {'op': 'subscribe', 'args': ['orderBookL2_25.BTCUSDT']}}
2020-12-03 08:48:27,381 : ERROR : BYBIT: Error from exchange {'success': False, 'ret_msg': 'error:invalid filter:BTCUSDT', 'conn_id': 'f5dd166f-a839-4880-9340-3cc931f5b306', 'request': {'op': 'subscribe', 'args': ['trade.BTCUSDT']}}
```

**Expected behavior**
Well, if channel or pair, either of them is not known, the usual error message indicating they are not known.
But I run `info()` method and they both appear to be ok.

```python
Bybit.info()
Out[2]: 
{'pairs': ['BTC-USD',
  'ETH-USD',
  'EOS-USD',
  'XRP-USD',
  'BTC-USDT',
  'ETH-USDT',
  'LTC-USDT',
  'XTZ-USDT',
  'LINK-USDT'],
 'channels': ['futures_index', 'l2_book', 'open_interest', 'trades'],
 'tick_size': {'BTC-USD': '0.5',
  'ETH-USD': '0.05',
  'EOS-USD': '0.001',
  'XRP-USD': '0.0001',
  'BTC-USDT': '0.5',
  'ETH-USDT': '0.05',
  'LTC-USDT': '0.01',
  'XTZ-USDT': '0.001',
  'LINK-USDT': '0.001'}}
```

**Operating System:**
Ubuntu 18.04

**Cryptofeed Version**
1.6.2
