### ISSUE TITLE
Gemini / Invalid message / 'auction_open'

### ISSUE THREAD

**Issue by yohplala** [bmoscon/cryptofeed#354]
**Describe the bug**
Getting warning message...
```bash
2020-12-14 04:00:00,052 : WARNING : GEMINI: Invalid message type {'type': 'auction_open', 'symbol': 'BTCUSD', 'auction_time_ms': 1607943600000, 'first_indicative_ms': 1607943000000, 'last_cancel_time_ms': 1607943540000}
2020-12-14 04:00:00,052 : WARNING : GEMINI: Invalid message type {'type': 'auction_open', 'symbol': 'BTCUSD', 'auction_time_ms': 1607943600000, 'first_indicative_ms': 1607943000000, 'last_cancel_time_ms': 1607943540000}
```

**To Reproduce**
... with config file.
```yaml
    GEMINI:
        retries: -1
        channel_timeouts:
            l2_book: 90
            trades: 90
        l2_book:
            symbols: ['BTC-USD']
            book_delta: true
            book_interval: 100000
        trades: ['BTC-USD']
```

**Expected behavior**
From time to time, I have this warning.
I got these 2 warnings within 8 hours.
Are they 'normal'?

**Operating System:**
Ubuntu 18.04

**Cryptofeed Version**
1.6.2
